name: Improved CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file exists
        run: test -f hello.txt

      - name: Simulate tests
        run: echo "All tests have got passed"

      - name: Final message
        run: echo "pipeline completed successfully"
